/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2021-12-05 09:29:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<div class=\"row\">\n");
      out.write("\t<div class=\"col-md-12 panel-warning\">\n");
      out.write("\t\t<div class=\"content-box-header panel-heading\">\n");
      out.write("\t\t\t<div class=\"panel-title \">Dashboard</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"content-box-large box-with-header\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-md-4 col-sm-4 col-xs-4\">\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-back noti-box\">\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-box bg-color-green set-icon\"> <span\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-th-list\"></span>\n");
      out.write("\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t<div class=\"text-box\">\n");
      out.write("\t\t\t\t\t\t\t<p class=\"main-text\">\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"fs-14\" href=\"cat.html\" title=\"\">Quản lý danh mục</a>\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t<p class=\"text-muted\">Có 4 danh mục</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-4 col-sm-4 col-xs-4\">\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-back noti-box\">\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-box bg-color-blue set-icon\"> <span\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-book\"></span>\n");
      out.write("\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t<div class=\"text-box\">\n");
      out.write("\t\t\t\t\t\t\t<p class=\"main-text\">\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"fs-14\" href=\"news.html\" title=\"\">Quản lý truyện</a>\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t<p class=\"text-muted\">Có 20 truyện</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-4 col-sm-4 col-xs-4\">\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-back noti-box\">\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-box bg-color-brown set-icon\"> <span\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></span>\n");
      out.write("\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t<div class=\"text-box\">\n");
      out.write("\t\t\t\t\t\t\t<p class=\"main-text\">\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"fs-14\" href=\"\" title=\"\">Quản lý người dùng</a>\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t<p class=\"text-muted\">Có 5 người dùng</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"row\">\n");
      out.write("\t<div class=\"col-md-6\">\n");
      out.write("\t\t<div class=\"content-box-large\">\n");
      out.write("\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t<div class=\"panel-title\">Chào mừng đến với trang quản trị</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"panel-options\">\n");
      out.write("\t\t\t\t\t<a href=\"#\" data-rel=\"collapse\"><i\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-refresh\"></i></a> <a href=\"#\"\n");
      out.write("\t\t\t\t\t\tdata-rel=\"reload\"><i class=\"glyphicon glyphicon-cog\"></i></a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\tUt tristique adipiscing mauris, sit amet suscipit metus porta quis.\n");
      out.write("\t\t\t\tDonec dictum tincidunt erat, eu blandit ligula. Nam sit amet dolor\n");
      out.write("\t\t\t\tsapien. Quisque velit erat, congue sed suscipit vel, feugiat sit\n");
      out.write("\t\t\t\tamet enim. Suspendisse interdum enim at mi tempor commodo. Sed\n");
      out.write("\t\t\t\ttincidunt sed tortor eu scelerisque. Donec luctus malesuada\n");
      out.write("\t\t\t\tvulputate. Nunc vel auctor metus, vel adipiscing odio. Aliquam\n");
      out.write("\t\t\t\taliquet rhoncus libero, at varius nisi pulvinar nec. Aliquam erat\n");
      out.write("\t\t\t\tvolutpat. Donec ut neque mi. Praesent enim nisl, bibendum vitae ante\n");
      out.write("\t\t\t\tet, placerat pharetra magna. Donec facilisis nisl turpis, eget\n");
      out.write("\t\t\t\tfacilisis turpis semper non. Maecenas luctus ligula tincidunt iasdsd\n");
      out.write("\t\t\t\tvitae ante et, <br />\n");
      out.write("\t\t\t\t<br /> Interdum et malesuada fames ac ante ipsum primis in\n");
      out.write("\t\t\t\tfaucibus. Quisque sed consectetur erat. Maecenas in elementum\n");
      out.write("\t\t\t\tlibero. Sed consequat pellentesque ultricies. Ut laoreet vehicula\n");
      out.write("\t\t\t\tnisl sed placerat. Duis posuere lectus n, eros et hendrerit\n");
      out.write("\t\t\t\tpellentesque, ante magna condimentum sapien, eget ultrices eros\n");
      out.write("\t\t\t\tlibero non orci. Etiam varius diam lectus. <br />\n");
      out.write("\t\t\t\t<br />\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div class=\"col-md-6\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-md-12\">\n");
      out.write("\t\t\t\t<div class=\"content-box-header\">\n");
      out.write("\t\t\t\t\t<div class=\"panel-title\">Hướng dẫn sử dụng</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"content-box-large box-with-header\">\n");
      out.write("\n");
      out.write("\t\t\t\t\tPellentesque luctus quam quis consequat vulputate. Sed sit amet\n");
      out.write("\t\t\t\t\tdiam ipsum. Praesent in pellentesque diam, sit amet dignissim erat.\n");
      out.write("\t\t\t\t\tAliquam erat volutpat. Aenean laoreet metus leo, laoreet feugiat\n");
      out.write("\t\t\t\t\tenim suscipit quis. Praesent mauris mauris, ornare vitae tincidunt\n");
      out.write("\t\t\t\t\tsed, hendrerit eget augue. Nam nec vestibulum nisi, eu dignissim\n");
      out.write("\t\t\t\t\tnulla. <br />\n");
      out.write("\t\t\t\t\t<br />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-md-12\">\n");
      out.write("\t\t\t\t<div class=\"content-box-header\">\n");
      out.write("\t\t\t\t\t<div class=\"panel-title\">Nội quy</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"content-box-large box-with-header\">\n");
      out.write("\n");
      out.write("\t\t\t\t\tPellentesque luctus quam quis consequat vulputate. Sed sit amet\n");
      out.write("\t\t\t\t\tdiam ipsum. Praesent in pellentesque diam, sit amet dignissim erat.\n");
      out.write("\t\t\t\t\tAliquam erat volutpat. Aenean laoreet metus leo, laoreet feugiat\n");
      out.write("\t\t\t\t\tenim suscipit quis. Praesent mauris mauris, ornare vitae tincidunt\n");
      out.write("\t\t\t\t\tsed, hendrerit eget augue. Nam nec vestibulum nisi, eu dignissim\n");
      out.write("\t\t\t\t\tnulla. <br />\n");
      out.write("\t\t\t\t\t<br />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
