/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2021-12-05 09:38:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class news_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<div class=\"content-box-large\">\n");
      out.write("\t<div class=\"row\">\n");
      out.write("\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t<div class=\"panel-title \">Quản lý truyện</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<hr>\n");
      out.write("\t<div class=\"row\">\n");
      out.write("\t\t<div class=\"col-md-8\">\n");
      out.write("\t\t\t<a href=\"add.html\" class=\"btn btn-success\"><span\n");
      out.write("\t\t\t\tclass=\"glyphicon glyphicon-plus\" aria-hidden=\"true\"></span>&nbsp;Thêm</a>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t<div class=\"input-group form\">\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Search...\">\n");
      out.write("\t\t\t\t<span class=\"input-group-btn\">\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary\" type=\"button\">Search</button>\n");
      out.write("\t\t\t\t</span>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div class=\"row\">\n");
      out.write("\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"\n");
      out.write("\t\t\t\tclass=\"table table-striped table-bordered\" id=\"example\">\n");
      out.write("\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<th>ID</th>\n");
      out.write("\t\t\t\t\t\t<th>Tên</th>\n");
      out.write("\t\t\t\t\t\t<th>Danh mục</th>\n");
      out.write("\t\t\t\t\t\t<th>Lượt đọc</th>\n");
      out.write("\t\t\t\t\t\t<th>Hình ảnh</th>\n");
      out.write("\t\t\t\t\t\t<th>Chức năng</th>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</thead>\n");
      out.write("\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t<tr class=\"odd gradeX\">\n");
      out.write("\t\t\t\t\t\t<td>1</td>\n");
      out.write("\t\t\t\t\t\t<td>Internet Explorer 4.0</td>\n");
      out.write("\t\t\t\t\t\t<td>Win 95+</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"center\">4</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"center text-center\"><img src=\"images/fff.png\" />\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"center text-center\"><a href=\"\" title=\"\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-primary\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-pencil \"></span> Sửa</a> <a href=\"\"\n");
      out.write("\t\t\t\t\t\t\ttitle=\"\" class=\"btn btn-danger\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-trash\"></span> Xóa</a></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr class=\"even gradeC\">\n");
      out.write("\t\t\t\t\t\t<td>2</td>\n");
      out.write("\t\t\t\t\t\t<td>Internet Explorer 5.0</td>\n");
      out.write("\t\t\t\t\t\t<td>Win 95+</td>\n");
      out.write("\t\t\t\t\t\t<td>95</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"center text-center\"><img src=\"images/fff.png\" />\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"center text-center\"><a href=\"\" title=\"\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-primary\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-pencil \"></span> Sửa</a> <a href=\"\"\n");
      out.write("\t\t\t\t\t\t\ttitle=\"\" class=\"btn btn-danger\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-trash\"></span> Xóa</a></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr class=\"odd gradeA\">\n");
      out.write("\t\t\t\t\t\t<td>3</td>\n");
      out.write("\t\t\t\t\t\t<td>Internet Explorer 5.5</td>\n");
      out.write("\t\t\t\t\t\t<td>Win 95+</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"center\">5.5</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"center text-center\"><img src=\"images/fff.png\" />\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"center text-center\"><a href=\"\" title=\"\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-primary\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-pencil\"></span> Sửa</a> <a href=\"\"\n");
      out.write("\t\t\t\t\t\t\ttitle=\"\" class=\"btn btn-danger\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-trash\"></span> Xóa</a></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr class=\"even gradeA\">\n");
      out.write("\t\t\t\t\t\t<td>4</td>\n");
      out.write("\t\t\t\t\t\t<td>Internet Explorer 6</td>\n");
      out.write("\t\t\t\t\t\t<td>Win 98+</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"center\">6</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"center text-center\"><img src=\"images/fff.png\" />\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"center text-center\"><a href=\"\" title=\"\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-primary\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-pencil \"></span> Sửa</a> <a href=\"\"\n");
      out.write("\t\t\t\t\t\t\ttitle=\"\" class=\"btn btn-danger\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-trash\"></span> Xóa</a></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr class=\"odd gradeA\">\n");
      out.write("\t\t\t\t\t\t<td>5</td>\n");
      out.write("\t\t\t\t\t\t<td>Internet Explorer 7</td>\n");
      out.write("\t\t\t\t\t\t<td>Win XP SP2+</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"center\">7</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"center text-center\"><img src=\"images/fff.png\" />\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"center text-center\"><a href=\"\" title=\"\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-primary\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-pencil \"></span> Sửa</a> <a href=\"\"\n");
      out.write("\t\t\t\t\t\t\ttitle=\"\" class=\"btn btn-danger\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-trash\"></span> Xóa</a></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr class=\"even gradeA\">\n");
      out.write("\t\t\t\t\t\t<td>6</td>\n");
      out.write("\t\t\t\t\t\t<td>AOL browser (AOL desktop)</td>\n");
      out.write("\t\t\t\t\t\t<td>Win XP</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"center\">6</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"center text-center\"><img src=\"images/fff.png\" />\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"center text-center\"><a href=\"\" title=\"\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-primary\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-pencil \"></span> Sửa</a> <a href=\"\"\n");
      out.write("\t\t\t\t\t\t\ttitle=\"\" class=\"btn btn-danger\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-trash\"></span> Xóa</a></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</tbody>\n");
      out.write("\t\t\t</table>\n");
      out.write("\n");
      out.write("\t\t\t<!-- Pagination -->\n");
      out.write("\t\t\t<nav class=\"text-center\" aria-label=\"...\">\n");
      out.write("\t\t\t\t<ul class=\"pagination\">\n");
      out.write("\t\t\t\t\t<li class=\"disabled\"><a href=\"#\" aria-label=\"Previous\"><span\n");
      out.write("\t\t\t\t\t\t\taria-hidden=\"true\">«</span></a></li>\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"#\">1 <span class=\"sr-only\">(current)</span></a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">2</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">3</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">4</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">5</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" aria-label=\"Next\"><span aria-hidden=\"true\">»</span></a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</nav>\n");
      out.write("\t\t\t<!-- /.pagination -->\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- /.row -->\n");
      out.write("</div>\n");
      out.write("<!-- /.content-box-large -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
